/* Rendering and input. Open index.html directly, or serve as a static site. */
(()=>{'use strict';
const D=window.Dermaga,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
let s=D.fresh(),learn=false,paused=false,selected='key',path=[],target=null,keys=new Set(),last=0,frame=0,toastUntil=12000,sound=false,audio=null,modalPaused=false,hudStamp=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const atlas=new Image();atlas.src='assets/atlas.webp';atlas.onerror=()=>$('asset-error').hidden=false;
const colors={Fungsional:'#f3c570',Interaktif:'#77cfbe',Dekoratif:'#bdc5c5',Resource:'#f3c570'};
const objectiveHints=['Dekati kunci emas di sisi kiri dermaga. Tekan E atau klik kuncinya.','Buka peti di sisi kanan atas dermaga untuk mendapatkan bahan bakar.','Dekati pintu di tengah jembatan. Kunci akan digunakan untuk membuka akses.','Seberangi jembatan, lalu isi generator di pulau mercusuar.','Dekati mercusuar dan aktifkan cahayanya.','Misi berhasil. Buka Mode belajar untuk membedah properti yang kamu gunakan.'];
function tone(ok){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(ok?560:190,audio.currentTime);o.frequency.exponentialRampToValueAtTime(ok?880:130,audio.currentTime+.16);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.2);}catch{sound=false;$('sound').setAttribute('aria-pressed','false');}}
function notify(result){$('toast').innerHTML='';const b=document.createElement('b'),span=document.createElement('span');b.textContent=result.title;span.textContent=result.text;$('toast').append(b,span);$('toast').classList.remove('fade');toastUntil=performance.now()+6500;if('ok'in result)tone(result.ok);}
function changeTab(name){document.querySelectorAll('[data-tab]').forEach(b=>{const yes=b.dataset.tab===name;b.setAttribute('aria-selected',yes);b.tabIndex=yes?0:-1;$('panel-'+b.dataset.tab).hidden=!yes;});}
function setLearn(value){learn=value;$('learn-mode').setAttribute('aria-pressed',value);$('play-mode').setAttribute('aria-pressed',!value);$('learn-mode').classList.toggle('selected',value);$('play-mode').classList.toggle('selected',!value);changeTab(value?'property':'mission');path=[];target=null;renderInspector();}
function stateText(o){switch(o.id){case'key':return s.key?'Tersimpan di inventori':s.keyTaken?'Sudah digunakan pada pintu':'Belum diambil';case'chest':return s.chestOpen?'Terbuka, isi sudah diambil':'Tertutup, berisi bahan bakar';case'door':return s.doorOpen?'Terbuka; jalur dapat dilewati':'Terkunci; membutuhkan kunci';case'generator':return s.generatorOn?'Hidup; listrik tersedia':'Mati; membutuhkan bahan bakar';case'lighthouse':return s.won?'Menyala; misi berhasil':s.generatorOn?'Listrik tersedia; siap dinyalakan':'Padam; listrik belum tersedia';case'medkit':return s.med?'Obat tersimpan':s.medTaken?'Obat sudah digunakan':'Belum diambil';case'lamp':return s.lampOn?'Menyala':'Padam';default:return 'Tersedia di lingkungan';}}
function renderInspector(){const o=D.OBJECTS.find(o=>o.id===selected);$('object-select').value=o.id;const box=$('inspector');box.innerHTML='';const title=document.createElement('h3');title.textContent=o.name;box.append(title);const tags=document.createElement('div');tags.className='tags';o.tags.forEach(t=>{const el=document.createElement('span');el.className='tag '+(t==='Interaktif'?'interactive':t==='Dekoratif'?'decorative':'');el.textContent=t;tags.append(el);});box.append(tags);const dl=document.createElement('dl');[['Fungsi',o.role],['Aturan & perilaku',o.rule],['Keadaan saat ini',stateText(o)],['Cerita dari lingkungan',o.story]].forEach(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;dl.append(dt,dd);});box.append(dl);if(o.action){const button=document.createElement('button');button.className='primary';button.textContent=o.action;button.disabled=s.won||s.failed||D.removed(s,o);button.onclick=()=>navigate(o);box.append(button);} }
function updateHUD(){ $('health-value').textContent=s.hp+' / 100';$('health-bar').style.width=s.hp+'%';$('health-bar').style.background=s.hp<30?'#e99473':'var(--gold)';const secs=Math.floor(s.elapsed);$('timer').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0');[['inv-key',s.key],['inv-fuel',s.fuel],['use-med',s.med]].forEach(([id,has])=>{$(id).classList.toggle('has',has);$(id).querySelector('b').textContent=has?'1':'—';});$('use-med').disabled=!s.med||s.won||s.failed;
 const n=D.STEPS.filter(([flag])=>s[flag]).length;$('progress-value').textContent=n+' / 5';$('progress-bar').style.width=n*20+'%';const next=D.STEPS.findIndex(([flag])=>!s[flag]);$('hint-text').textContent=objectiveHints[next<0?5:next];$('objectives').innerHTML=D.STEPS.map(([flag,title,desc],i)=>'<li class="'+(s[flag]?'done':i===next?'current':'')+'"><span class="objective-num">'+(s[flag]?'✓':String(i+1).padStart(2,'0'))+'</span><div><b>'+title+'</b><small>'+desc+'</small></div></li>').join('');
}
function endScreen(){keys.clear();path=[];target=null;$('overlay').hidden=false;$('overlay-kicker').textContent=s.won?'MISI BERHASIL':'MISI BERAKHIR';$('overlay-title').textContent=s.won?'Cahaya membawa pulang.':'Kondisi Raka habis.';$('overlay-text').textContent=s.won?'Perahu terakhir menemukan dermaga. Kamu telah menghubungkan properti, aturan, resource, dan tujuan permainan.':'Ambil obat lebih awal dan pilih rute yang menghindari tumpahan oli.';$('resume').textContent=s.won?'Bedah permainan':'Coba lagi';}
function interact(o){if(paused||modalPaused)return;selected=o.id;notify(D.act(s,o.id));renderInspector();updateHUD();if(s.won)endScreen();}
function navigate(o){selected=o.id;renderInspector();if(paused||modalPaused||s.won||s.failed)return;if(D.removed(s,o)){notify({title:o.name,text:'Objek ini sudah diambil.'});return;}if(Math.hypot(s.player.x-o.x,s.player.y-o.y)<=68){interact(o);return;}const p=D.findPath(s,o.x,o.y,62);if(!p){notify({ok:false,title:'Jalur belum terbuka',text:'Buka pintu jembatan dengan kunci sebelum menuju mercusuar.'});return;}path=p;target=o;}
function nearest(){return D.OBJECTS.filter(o=>o.action&&!D.removed(s,o)).map(o=>({o,d:Math.hypot(o.x-s.player.x,o.y-s.player.y)})).sort((a,b)=>a.d-b.d)[0];}
function interactNear(){const n=nearest();if(n&&n.d<=72)interact(n.o);else notify({title:'Belum ada objek dalam jangkauan',text:'Dekati objek lalu tekan E. Kamu juga bisa mengklik objeknya.'});}
function restart(){s=D.fresh();paused=false;path=[];target=null;keys.clear();$('overlay').hidden=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Jeda permainan');renderInspector();updateHUD();notify({title:'Misi dimulai kembali',text:'Cari kunci, buka peti, lalu pulihkan cahaya mercusuar.'});}
function pause(){if(s.won||s.failed||modalPaused)return;paused=!paused;path=[];target=null;keys.clear();$('overlay').hidden=!paused;$('pause').textContent=paused?'▷':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Lanjutkan permainan':'Jeda permainan');$('overlay-kicker').textContent='JEDA';$('overlay-title').textContent='Ambil napas sebentar.';$('overlay-text').textContent='Waktu dan kondisi berhenti selama permainan dijeda.';$('resume').textContent='Lanjutkan permainan';}
function openDialog(id){modalPaused=true;keys.clear();$(id).showModal();}
function closeDialog(id){$(id).close();modalPaused=false;last=performance.now();}
function sprite(name,x,y,w,alpha=1,brightness=1){if(!atlas.complete||!atlas.naturalWidth)return;const a=D.SPRITES[name],h=w*a[3]/a[2];ctx.save();ctx.globalAlpha=alpha;ctx.filter=brightness===1?'none':'brightness('+brightness+')';ctx.imageSmoothingEnabled=true;ctx.drawImage(atlas,...a,x-w/2,y-h,w,h);ctx.restore();}
function ellipse(x,y,rx,ry,color){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function round(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,2*r,2*r);}
function draw(now){const t=reduced?0:now/1000;ctx.clearRect(0,0,960,600);ctx.fillStyle='#244e57';ctx.fillRect(0,0,960,600);
 // Water is a deterministic tiled field, so the scene works without network assets.
 for(let y=0;y<600;y+=30)for(let x=0;x<960;x+=40){const seed=(x*3+y*7)%97;ctx.fillStyle=seed%3===0?'#2b5860':'#29535c';ctx.fillRect(x,y,40,30);if(seed%5===0){ctx.strokeStyle='#82b8b32b';ctx.lineWidth=1;ctx.beginPath();const dx=Math.sin(t*.7+seed)*4;ctx.moveTo(x+dx,y+15);ctx.lineTo(x+17+dx,y+15);ctx.stroke();}}
 ctx.save();ctx.font='italic 19px Georgia';ctx.fillStyle='#bdd1c056';ctx.fillText('Sungai Muara Senja',55,554);ctx.restore();
 // Land footprints and boardwalks; collision uses the same LAND definitions.
 for(const r of D.LAND){round(r.x-7,r.y+10,r.w+14,r.h+10,5,'#112d35a6');round(r.x-4,r.y-4,r.w+8,r.h+8,4,'#203a36');ctx.fillStyle='#9c8158';ctx.fillRect(r.x,r.y,r.w,r.h);for(let y=r.y;y<r.y+r.h;y+=14){ctx.fillStyle=(y/14|0)%3===0?'#a78a5f':'#aa9067';ctx.fillRect(r.x+2,y+2,r.w-4,11);ctx.strokeStyle='#6d5c443f';ctx.lineWidth=1;for(let x=r.x+22;x<r.x+r.w-5;x+=60){ctx.beginPath();ctx.moveTo(x,y+7);ctx.lineTo(x+21,y+7);ctx.stroke();}ctx.fillStyle='#68554188';ctx.fillRect(r.x+6,y+5,2,2);ctx.fillRect(r.x+r.w-8,y+5,2,2);}}
 // Edges and posts emphasize the visible movement boundary.
 ctx.fillStyle='#716146';for(let x=82;x<555;x+=42){ctx.fillRect(x,157,8,7);ctx.fillRect(x,497,8,11);}for(let x=572;x<754;x+=37){ctx.fillRect(x,296,7,9);ctx.fillRect(x,399,7,10);}ctx.strokeStyle='#ccb083';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(565,297);ctx.lineTo(757,297);ctx.moveTo(565,402);ctx.lineTo(757,402);ctx.stroke();
 // Moss patches define the land's age without interfering with the walking path.
 for(let i=0;i<32;i++){const x=85+(i*67)%460,y=i%2?166+(i*11)%20:476+(i*7)%16;ctx.fillStyle=i%3?'#587453':'#648457';ctx.fillRect(x,y,6+i%8,3+i%5);}round(763,164,150,13,2,'#658064');
 ellipse(397,346,37,22,'#3c4143b8');ellipse(390,340,23,14,'#2b3639');ctx.strokeStyle='#beaa7266';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(398,345,29,13,.3,0,6.28);ctx.stroke();
 if(path.length){ctx.save();ctx.setLineDash([3,8]);ctx.strokeStyle='#fce0a98f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.player.x,s.player.y);path.forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.restore();}
 const list=D.OBJECTS.filter(o=>o.sprite&&!D.removed(s,o)).map(o=>({...o,kind:'object'}));list.push({id:'player',x:s.player.x,y:s.player.y,kind:'player'});list.sort((a,b)=>a.y-b.y);
 const near=nearest();
 for(const o of list){if(o.kind==='player'){ellipse(o.x,o.y+2,14,6,'#172d3077');if(!path.length){ctx.strokeStyle='#f9d47c88';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(o.x,o.y,18,8,0,0,6.28);ctx.stroke();}const bob=(keys.size||path.length)&&!reduced?Math.sin(t*14)*1.5:0;sprite('player'+s.player.dir,o.x,o.y+bob,31);continue;}
 ellipse(o.x,o.y+1,o.w*.31,o.w*.1,'#172e3b55');if((learn&&selected===o.id)||(!learn&&near?.o.id===o.id&&near.d<72)){ctx.strokeStyle=colors[o.tags[0]];ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(o.x,o.y+2,o.w*.52+8,13,0,0,6.28);ctx.stroke();}
 let name=o.sprite,brightness=1;if(o.id==='chest'&&s.chestOpen)name='chestOpen';if(o.id==='door'&&s.doorOpen)name='doorOpen';if(o.id==='lamp'&&!s.lampOn)brightness=.42;if(o.id==='lighthouse'&&!s.won)brightness=.56;
 if(o.id==='lamp'&&s.lampOn)glow(o.x,o.y-48,65,'#ffe6a226');if(o.id==='lighthouse'&&s.won)glow(o.x,o.y-128,120,'#ffe58c85');if(o.id==='key')glow(o.x,o.y-17,34,'#fff09940');sprite(name,o.x,o.y,o.w,1,brightness);
 if(o.id==='generator'&&s.generatorOn){glow(o.x+14,o.y-27,22,'#84e7b979');ellipse(o.x+14,o.y-27,3,3,'#a1ebc6');}
 }
 if(s.won){ctx.save();ctx.translate(839,108);ctx.rotate(reduced?-.5:t*.25);const beam=ctx.createLinearGradient(0,0,430,0);beam.addColorStop(0,'#fff6b866');beam.addColorStop(1,'#fff6b800');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(430,-80);ctx.lineTo(430,80);ctx.closePath();ctx.fill();ctx.restore();}
 if(learn){for(const o of D.OBJECTS){if(D.removed(s,o))continue;const text=o.name;ctx.font='11px "Segoe UI",Arial';const w=ctx.measureText(text).width+16;const yy=o.id==='oil'?o.y+32:o.y+17;round(o.x-w/2,yy-11,w,19,4,'#102832e8');ctx.fillStyle=colors[o.tags[0]];ctx.textAlign='center';ctx.fillText(text,o.x,yy+2);ctx.textAlign='left';}}
 else if(near&&near.d<72&&!s.won&&!s.failed){ctx.font='bold 12px "Segoe UI",Arial';const text='E · '+near.o.action,w=ctx.measureText(text).width+20;const x=Math.min(950-w,Math.max(10,s.player.x-w/2));round(x,s.player.y-78,w,23,5,'#152b35ed');ctx.fillStyle='#f9d791';ctx.fillText(text,x+10,s.player.y-62);}
 // Vignette keeps the boardwalk lit and the surrounding river subdued.
 const vignette=ctx.createRadialGradient(470,320,210,470,320,660);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#091c3377');ctx.fillStyle=vignette;ctx.fillRect(0,0,960,600);
}
function loop(now){const dt=Math.min((now-(last||now))/1000,.045);last=now;const active=!paused&&!modalPaused&&!document.hidden&&!s.won&&!s.failed; if(active){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy){path=[];target=null;const len=Math.hypot(dx,dy);dx=dx/len*145*dt;dy=dy/len*145*dt;}else if(path.length){const p=path[0],vx=p.x-s.player.x,vy=p.y-s.player.y,len=Math.hypot(vx,vy);if(len<3){path.shift();if(!path.length&&target){const o=target;target=null;interact(o);}}else{dx=vx/len*Math.min(145*dt,len);dy=vy/len*Math.min(145*dt,len);}}if(dx||dy){s.player.dir=Math.abs(dx)>Math.abs(dy)?dx>0?'Right':'Left':dy>0?'Down':'Up';D.move(s,dx,dy);}const hp=s.hp;D.tick(s,dt);if(s.hp<hp){notify({ok:false,title:'Hati-hati, tumpahan oli',text:'Kondisi berkurang. Menjauh atau gunakan obat dengan Q.'});if(s.failed)endScreen();}}
 if(now>toastUntil)$('toast').classList.add('fade');if(now-hudStamp>250){updateHUD();hudStamp=now;}draw(now);frame=requestAnimationFrame(loop);
}
canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});if(paused||modalPaused||s.failed)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*600/r.height;const o=[...D.OBJECTS].reverse().find(o=>{if(D.removed(s,o))return false;const h=o.sprite?o.w*D.SPRITES[o.sprite][3]/D.SPRITES[o.sprite][2]:40;return x>=o.x-o.w/2-10&&x<=o.x+o.w/2+10&&y>=o.y-h-5&&y<=o.y+13;});if(o){selected=o.id;renderInspector();if(learn){changeTab('property');return;}navigate(o);}else if(!s.won){const p=D.findPath(s,x,y,18);if(p){path=p;target=null;}else notify({title:'Di luar jalur',text:'Raka hanya dapat berjalan di area dermaga. Buka pintu untuk ke seberang.'});}});
document.addEventListener('keydown',e=>{if(e.target.matches('select,input,textarea')||modalPaused)return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){if(e.target.closest('[role=tablist]'))return;e.preventDefault();keys.add(k);}if(e.repeat)return;if(k==='e'){e.preventDefault();interactNear();}if(k==='q'&&!paused&&!s.won&&!s.failed){notify(D.heal(s));updateHUD();renderInspector();}if(k==='p')pause();if(k==='?')openDialog('help-dialog');});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();last=performance.now();});
$('play-mode').onclick=()=>setLearn(false);$('learn-mode').onclick=()=>setLearn(true);$('pause').onclick=pause;$('resume').onclick=()=>{if(s.won){$('overlay').hidden=true;setLearn(true);}else if(s.failed)restart();else pause();};$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',sound);$('sound').setAttribute('aria-label',sound?'Matikan suara':'Nyalakan suara');$('sound').title=sound?'Matikan suara':'Nyalakan suara';tone(true);};$('use-med').onclick=()=>{if(!paused&&!modalPaused){notify(D.heal(s));updateHUD();renderInspector();}};$('touch-interact').onclick=interactNear;
document.querySelectorAll('[data-move]').forEach(b=>{const key={up:'arrowup',down:'arrowdown',left:'arrowleft',right:'arrowright'}[b.dataset.move];b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(key);});
document.querySelectorAll('[data-tab]').forEach((b,i)=>{b.onclick=()=>changeTab(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],j=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;changeTab(tabs[j].dataset.tab);tabs[j].focus();}};});
for(const o of D.OBJECTS){const option=document.createElement('option');option.value=o.id;option.textContent=o.name;$('object-select').append(option);}$('object-select').onchange=e=>{selected=e.target.value;renderInspector();};
$('help').onclick=()=>openDialog('help-dialog');document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>closeDialog('help-dialog'));$('restart').onclick=()=>openDialog('reset-dialog');$('cancel-reset').onclick=()=>closeDialog('reset-dialog');$('confirm-reset').onclick=()=>{closeDialog('reset-dialog');restart();};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{modalPaused=false;last=performance.now();}));
renderInspector();updateHUD();frame=requestAnimationFrame(loop);
// Progressive enhancement: safe, read-only structured inspection for supporting agents.
if(navigator.modelContext?.registerTool){navigator.modelContext.registerTool({name:'inspect_dermaga',description:'Read current mission progress and educational property definitions.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({hp:s.hp,progress:D.STEPS.map(([flag,name])=>({name,complete:s[flag]})),properties:D.OBJECTS.map(({id,name,tags,role,rule})=>({id,name,tags,role,rule}))})}]})});}
})();
